skip_branch_with_pr: true

environment:
  MODE: test
  PYTHON_VERSION: C:\Python36-x64
  NUMPY_VERSION: numpy
  TF_VERSION: tensorflow>=2.0.0b1
  NENGO_VERSION: nengo[tests]

  matrix:
    - MODE: test # default build
    - NENGO_VERSION: git+https://github.com/nengo/nengo.git@pytest-plt-rng#egg=nengo[tests]
      TF_VERSION: tensorflow>=2.0.0b1 --pre
    - NENGO_VERSION: nengo[tests]==2.8.0
      TF_VERSION: tensorflow==2.0.0b1
      NUMPY_VERSION: numpy==1.16
      PYTHON_VERSION: C:\Python35-x64

init:
  - set PATH=%PYTHON_VERSION%;%PYTHON_VERSION%\Scripts;%PATH%

install:
  - python -m pip install pip setuptools --upgrade
  - pip install %NUMPY_VERSION% %TF_VERSION% %NENGO_VERSION%
  - pip install -e .[tests]
  - pip freeze

build: false  # Not a C# project

test_script:
  - pytest -n 2 --pyargs nengo && pytest -n 2 --durations 20 nengo_dl
